<a href="https://colab.research.google.com/github/Deepanshu-Malakar/Learn_Machine_Learning/blob/main/intro_to_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)



2.4.0+cu121


In [3]:
#introduction
scalar=torch.tensor(7)
print(scalar)

tensor(7)


Properties of Scalars

In [4]:
#to get dimension of tensor
print("dimension of scalar is :",scalar.ndim)
#to get tensor back as integer
print("value of scalar is: ",scalar.item())

dimension of scalar is : 0
value of scalar is:  7


vector

In [5]:
vector=torch.tensor([7,7])
print(vector)
print("dimension of vector :",vector.ndim)
print("shape of vector : ",vector.shape)
vector2=torch.tensor([[2,4,3],
                     [4,5,3]])
print(vector2)
print("dimension of vector2 :",vector2.ndim)
print("shape of vector2 : ",vector2.shape)

tensor([7, 7])
dimension of vector : 1
shape of vector :  torch.Size([2])
tensor([[2, 4, 3],
        [4, 5, 3]])
dimension of vector2 : 2
shape of vector2 :  torch.Size([2, 3])


Random tensors


In [6]:
random_tensor = torch.rand(4,3,3)
print(random_tensor)

tensor([[[0.7381, 0.5394, 0.3507],
         [0.0861, 0.5097, 0.7559],
         [0.7506, 0.8077, 0.4990]],

        [[0.1851, 0.0138, 0.9520],
         [0.3898, 0.0571, 0.7660],
         [0.4972, 0.1974, 0.1110]],

        [[0.0412, 0.4118, 0.3240],
         [0.5922, 0.0600, 0.2629],
         [0.8148, 0.3520, 0.7463]],

        [[0.8039, 0.8597, 0.2476],
         [0.8155, 0.5481, 0.1950],
         [0.8679, 0.8321, 0.1402]]])


Image tensor

In [7]:
random_image_tensor=torch.rand(size=(224,224,3)) #height width color_channels(rgb)
print("shape: ",random_image_tensor.shape)
print("dimension: ",random_image_tensor.ndim)

shape:  torch.Size([224, 224, 3])
dimension:  3


**Zeroes and Ones**

In [8]:
zeroes=torch.zeros(3,4)
ones=torch.ones(3,4)
print(zeroes)
print("\n")
print(ones)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating Range of tensors

In [9]:
#use torch.arange(start,end,step)   creates an AP with a=start an=end d=step
#  doesnot include the end element
range1=torch.arange(start=1,end=21,step=2)
print(range1)
range2=torch.arange(start=5,end=32,step=4)
print(range2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor([ 5,  9, 13, 17, 21, 25, 29])


Tensors like (creating a tensor with same shape like another tensor)

In [10]:
tensor_like=torch.rand_like(input=random_tensor)
print(tensor_like)

tensor([[[0.5022, 0.1645, 0.2412],
         [0.7365, 0.6141, 0.4867],
         [0.9474, 0.7910, 0.0257]],

        [[0.6388, 0.8525, 0.1172],
         [0.2415, 0.1868, 0.9572],
         [0.6839, 0.8922, 0.6620]],

        [[0.1571, 0.3223, 0.6591],
         [0.3043, 0.4206, 0.1749],
         [0.7749, 0.5894, 0.6543]],

        [[0.1144, 0.5178, 0.6658],
         [0.2549, 0.0770, 0.9814],
         [0.6947, 0.5770, 0.2638]]])


**Getting Information from tensors**
1)Tensor Manupulation *(Tensor operations)*

In [11]:
t=torch.tensor([1,2,3,4])
print("tensor: ",t)
print("tensor + 1: ",t+1)
print("tensor - 1: ",t-1)
print("tensor * 10: ",t*10)
print("tensor / 10: ",t/10)


tensor:  tensor([1, 2, 3, 4])
tensor + 1:  tensor([2, 3, 4, 5])
tensor - 1:  tensor([0, 1, 2, 3])
tensor * 10:  tensor([10, 20, 30, 40])
tensor / 10:  tensor([0.1000, 0.2000, 0.3000, 0.4000])


Matrix Multiplication

In [12]:
#element wise matrix multiplication
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(f"{tensor1}*{tensor2}={tensor1*tensor2}")


tensor([1, 2, 3])*tensor([4, 5, 6])=tensor([ 4, 10, 18])


Dot product of tensors

In [13]:
print(tensor1.matmul(tensor2))
print("note that 32=4+10+18")

tensor(32)
note that 32=4+10+18


In [14]:
tensor1=torch.randint(low=0,high=5,size=(2,3))
tensor2=torch.randint(low=0,high=5,size=(3,4))
print("tensor1:")
print(tensor1)
print("tensor2:")
print(tensor2)
print(f"tensor1 x tensor2 =\n{tensor1.matmul(tensor2)}")

tensor1:
tensor([[2, 3, 3],
        [4, 2, 2]])
tensor2:
tensor([[2, 4, 4, 4],
        [3, 2, 2, 0],
        [4, 0, 0, 4]])
tensor1 x tensor2 =
tensor([[25, 14, 14, 20],
        [22, 20, 20, 24]])


Finding min , max , mean , sum of tensors (tensor aggregation)

In [15]:
print("tensor: ")
print(tensor1)
print(f"min : {tensor1.min()}")
print(f"max : {tensor1.max()}")
print(f"mean : {tensor1.type(torch.float32).mean()}")   #note mean requires float32 type tensor

#to change data type of a tensor write
print("float 32 tensor is: ")
print(tensor1.type(torch.float32))

tensor: 
tensor([[2, 3, 3],
        [4, 2, 2]])
min : 2
max : 4
mean : 2.6666667461395264
float 32 tensor is: 
tensor([[2., 3., 3.],
        [4., 2., 2.]])


# **Positional min and max**
find the position of minimum and maximum element in the tensor.
use argmin() and argmax() functions

In [16]:
print(f"tensor:\n{tensor1}")
print(f"min index : {tensor1.argmin()} and minimum element is {tensor1.min()}")
print(f"max index : {tensor1.argmax()} and maximum element is {tensor1.max()}")

tensor2=torch.tensor([[1,3,5],
                      [6,1,3]])
print("\n")
print(f"tensor:\n{tensor2}")
print(f"min index : {tensor2.argmin()} and minimum element is {tensor2.min()}")
print(f"max index : {tensor2.argmax()} and maximum element is {tensor2.max()}")


tensor:
tensor([[2, 3, 3],
        [4, 2, 2]])
min index : 0 and minimum element is 2
max index : 3 and maximum element is 4


tensor:
tensor([[1, 3, 5],
        [6, 1, 3]])
min index : 0 and minimum element is 1
max index : 3 and maximum element is 6


#reshaping stacking squezing and unsquezing tensors


1.   **reshaping** - change the shape of tensor to a new shape
2. **view** - view a tensor in new shape but it change the original tensor
3.   **stacking** - combining multiple tensors on top of each other-(vstack)   side by side-(hstack)
4.  **squeze**- remove 1 dimension from tensor
5.  **unsqueze** - add 1 dimension to a tensor
6. **permute**- return the view of input with dimensions permutted i,e swapped in a certain way.



In [17]:
x=torch.arange(1,10,1)
print(x)
y=x.reshape(3,3) #note new dimensions must be compatible with the old dimensions you cannot provide new dimensions like  1,7 since 1*7=7 and we have 9 elements in our tensor
print("tensor reshaped as (3,3)")
print(y)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor reshaped as (3,3)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [18]:
#view
print(x)
z=x.view(3,3)
print(x)
print(z)
z[0]=5
print(x)
print(z)
#x and z shares the same location and hence changing z will change x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([5, 5, 5, 4, 5, 6, 7, 8, 9])
tensor([[5, 5, 5],
        [4, 5, 6],
        [7, 8, 9]])


In [19]:
#stack tensors on top of each other
print(x,"\n")
z=torch.stack([x,x])
print(z,"\n")
z=torch.stack([x,x,x])
print(z,"\n")
z=torch.stack([x,x],dim=1)
print(z,"\n")
z=torch.stack([x,x,x],dim=1)
print(z,"\n")

tensor([5, 5, 5, 4, 5, 6, 7, 8, 9]) 

tensor([[5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9]]) 

tensor([[5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9]]) 

tensor([[5, 5],
        [5, 5],
        [5, 5],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]]) 

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]) 



In [21]:
#squezing tensors
print(x,"\n")
z=x+2
z=torch.stack([x,z,z*2])
print(z,"\n")
print(z.squeeze(),"\n")
z=z.reshape(1,3,9)
print(z,"\n")
z=z.squeeze()
print(z,"\n")


tensor([5, 5, 5, 4, 5, 6, 7, 8, 9]) 

tensor([[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
        [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
        [14, 14, 14, 12, 14, 16, 18, 20, 22]]) 

tensor([[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
        [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
        [14, 14, 14, 12, 14, 16, 18, 20, 22]]) 

tensor([[[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
         [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
         [14, 14, 14, 12, 14, 16, 18, 20, 22]]]) 

tensor([[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
        [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
        [14, 14, 14, 12, 14, 16, 18, 20, 22]]) 



In [24]:
#unsqueze
tensor=torch.randint(low=5,high=45,size=(3,4))
print(f"original tensor: \n{tensor} \nshape={tensor.shape}")
print(f"unsquezed at dim 0:\n{tensor.unsqueeze(dim=0)}\nshape = {tensor.unsqueeze(dim=0).shape}")
print(f"unsquezed at dim 1:\n{tensor.unsqueeze(dim=1)}\nshape = {tensor.unsqueeze(dim=1).shape}")

original tensor: 
tensor([[28, 17, 12, 10],
        [35, 16, 34, 40],
        [11, 13, 26, 11]]) 
shape=torch.Size([3, 4])
unsquezed at dim 0:
tensor([[[28, 17, 12, 10],
         [35, 16, 34, 40],
         [11, 13, 26, 11]]])
shape = torch.Size([1, 3, 4])
unsquezed at dim 1:
tensor([[[28, 17, 12, 10]],

        [[35, 16, 34, 40]],

        [[11, 13, 26, 11]]])
shape = torch.Size([3, 1, 4])


#**Permute**
permute changes the order of dimensions of a tensor<br>
**Example:**<br>
For an image tensor, we write torch.rand(size=(244,244,3)) i,e height,width, and color channels.<br>
For some reason now you want it as color channel,width,height ,<br>
you can do this using **permute**<br>
**note :**<br>
 if you change anything in the permuted tensor, the original tensor will change as well

In [27]:
x=torch.rand(size=(255,255,3))
print(f"shape of tensor: {x.shape}")
x_permuted=x.permute(2,0,1)
print(f"shape of permuted tensor: {x_permuted.shape}\n")
y=torch.rand(3,2,1)
print(f"shape of original tensor: {y.shape}")
y_permuted=y.permute(2,0,1)  #2nd dimension becomes 0th dimension , 0th becomes 1st and 1st becomes 2nd dimension
print(f"shape of permuted tensor: {y_permuted.shape}")

shape of tensor: torch.Size([255, 255, 3])
shape of permuted tensor: torch.Size([3, 255, 255])

shape of original tensor: torch.Size([3, 2, 1])
shape of permuted tensor: torch.Size([1, 3, 2])
