<a href="https://colab.research.google.com/github/Deepanshu-Malakar/Learn_Machine_Learning/blob/main/intro_to_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)



2.4.0+cu121


In [5]:
#introduction
scalar=torch.tensor(7)
print(scalar)

tensor(7)


Properties of Scalars

In [6]:
#to get dimension of tensor
print("dimension of scalar is :",scalar.ndim)
#to get tensor back as integer
print("value of scalar is: ",scalar.item())

dimension of scalar is : 0
value of scalar is:  7


vector

In [7]:
vector=torch.tensor([7,7])
print(vector)
print("dimension of vector :",vector.ndim)
print("shape of vector : ",vector.shape)
vector2=torch.tensor([[2,4,3],
                     [4,5,3]])
print(vector2)
print("dimension of vector2 :",vector2.ndim)
print("shape of vector2 : ",vector2.shape)

tensor([7, 7])
dimension of vector : 1
shape of vector :  torch.Size([2])
tensor([[2, 4, 3],
        [4, 5, 3]])
dimension of vector2 : 2
shape of vector2 :  torch.Size([2, 3])


Random tensors


In [8]:
random_tensor = torch.rand(4,3,3)
print(random_tensor)

tensor([[[0.1397, 0.5479, 0.0854],
         [0.2239, 0.8903, 0.5136],
         [0.6869, 0.0796, 0.2853]],

        [[0.0055, 0.1481, 0.7302],
         [0.3547, 0.5276, 0.8882],
         [0.0181, 0.0804, 0.8437]],

        [[0.5183, 0.3224, 0.3596],
         [0.0097, 0.7672, 0.2761],
         [0.1389, 0.2322, 0.1007]],

        [[0.3289, 0.7317, 0.0948],
         [0.5507, 0.4067, 0.1304],
         [0.6642, 0.7919, 0.0703]]])


Image tensor

In [9]:
random_image_tensor=torch.rand(size=(224,224,3)) #height width color_channels(rgb)
print("shape: ",random_image_tensor.shape)
print("dimension: ",random_image_tensor.ndim)

shape:  torch.Size([224, 224, 3])
dimension:  3


**Zeroes and Ones**

In [10]:
zeroes=torch.zeros(3,4)
ones=torch.ones(3,4)
print(zeroes)
print("\n")
print(ones)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating Range of tensors

In [11]:
#use torch.arange(start,end,step)   creates an AP with a=start an=end d=step
#  doesnot include the end element
range1=torch.arange(start=1,end=21,step=2)
print(range1)
range2=torch.arange(start=5,end=32,step=4)
print(range2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor([ 5,  9, 13, 17, 21, 25, 29])


Tensors like (creating a tensor with same shape like another tensor)

In [12]:
tensor_like=torch.rand_like(input=random_tensor)
print(tensor_like)

tensor([[[0.1116, 0.5543, 0.6756],
         [0.1522, 0.7549, 0.4520],
         [0.2180, 0.5062, 0.6830]],

        [[0.9105, 0.7631, 0.1681],
         [0.4750, 0.8319, 0.4886],
         [0.7988, 0.3097, 0.4728]],

        [[0.6464, 0.6604, 0.5675],
         [0.4440, 0.2182, 0.9497],
         [0.0089, 0.5283, 0.2284]],

        [[0.6635, 0.1583, 0.9920],
         [0.8167, 0.0999, 0.5537],
         [0.9770, 0.6508, 0.1503]]])


**Getting Information from tensors**
1)Tensor Manupulation *(Tensor operations)*

In [13]:
t=torch.tensor([1,2,3,4])
print("tensor: ",t)
print("tensor + 1: ",t+1)
print("tensor - 1: ",t-1)
print("tensor * 10: ",t*10)
print("tensor / 10: ",t/10)


tensor:  tensor([1, 2, 3, 4])
tensor + 1:  tensor([2, 3, 4, 5])
tensor - 1:  tensor([0, 1, 2, 3])
tensor * 10:  tensor([10, 20, 30, 40])
tensor / 10:  tensor([0.1000, 0.2000, 0.3000, 0.4000])


Matrix Multiplication

In [14]:
#element wise matrix multiplication
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(f"{tensor1}*{tensor2}={tensor1*tensor2}")


tensor([1, 2, 3])*tensor([4, 5, 6])=tensor([ 4, 10, 18])


Dot product of tensors

In [15]:
print(tensor1.matmul(tensor2))
print("note that 32=4+10+18")

tensor(32)
note that 32=4+10+18


In [16]:
tensor1=torch.randint(low=0,high=5,size=(2,3))
tensor2=torch.randint(low=0,high=5,size=(3,4))
print("tensor1:")
print(tensor1)
print("tensor2:")
print(tensor2)
print(f"tensor1 x tensor2 =\n{tensor1.matmul(tensor2)}")

tensor1:
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor2:
tensor([[4, 3, 2, 4],
        [2, 3, 2, 2],
        [2, 1, 3, 3]])
tensor1 x tensor2 =
tensor([[4, 3, 2, 4],
        [4, 3, 2, 4]])


Finding min , max , mean , sum of tensors (tensor aggregation)

In [17]:
print("tensor: ")
print(tensor1)
print(f"min : {tensor1.min()}")
print(f"max : {tensor1.max()}")
print(f"mean : {tensor1.type(torch.float32).mean()}")   #note mean requires float32 type tensor

#to change data type of a tensor write
print("float 32 tensor is: ")
print(tensor1.type(torch.float32))

tensor: 
tensor([[1, 0, 0],
        [1, 0, 0]])
min : 0
max : 1
mean : 0.3333333432674408
float 32 tensor is: 
tensor([[1., 0., 0.],
        [1., 0., 0.]])


# **Positional min and max**
find the position of minimum and maximum element in the tensor.
use argmin() and argmax() functions

In [18]:
print(f"tensor:\n{tensor1}")
print(f"min index : {tensor1.argmin()} and minimum element is {tensor1.min()}")
print(f"max index : {tensor1.argmax()} and maximum element is {tensor1.max()}")

tensor2=torch.tensor([[1,3,5],
                      [6,1,3]])
print("\n")
print(f"tensor:\n{tensor2}")
print(f"min index : {tensor2.argmin()} and minimum element is {tensor2.min()}")
print(f"max index : {tensor2.argmax()} and maximum element is {tensor2.max()}")


tensor:
tensor([[1, 0, 0],
        [1, 0, 0]])
min index : 1 and minimum element is 0
max index : 0 and maximum element is 1


tensor:
tensor([[1, 3, 5],
        [6, 1, 3]])
min index : 0 and minimum element is 1
max index : 3 and maximum element is 6


#reshaping stacking squezing and unsquezing tensors


1.   **reshaping** - change the shape of tensor to a new shape
2. **view** - view a tensor in new shape but it change the original tensor
3.   **stacking** - combining multiple tensors on top of each other-(vstack)   side by side-(hstack)
4.  **squeze**- remove 1 dimension from tensor
5.  **unsqueze** - add 1 dimension to a tensor
6. **permute**- return the view of input with dimensions permutted i,e swapped in a certain way.



In [19]:
x=torch.arange(1,10,1)
print(x)
y=x.reshape(3,3) #note new dimensions must be compatible with the old dimensions you cannot provide new dimensions like  1,7 since 1*7=7 and we have 9 elements in our tensor
print("tensor reshaped as (3,3)")
print(y)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor reshaped as (3,3)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [20]:
#view
print(x)
z=x.view(3,3)
print(x)
print(z)
z[0]=5
print(x)
print(z)
#x and z shares the same location and hence changing z will change x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([5, 5, 5, 4, 5, 6, 7, 8, 9])
tensor([[5, 5, 5],
        [4, 5, 6],
        [7, 8, 9]])


In [28]:
#stack tensors on top of each other
print(x,"\n")
z=torch.stack([x,x])
print(z,"\n")
z=torch.stack([x,x,x])
print(z,"\n")
z=torch.stack([x,x],dim=1)
print(z,"\n")
z=torch.stack([x,x,x],dim=1)
print(z,"\n")

tensor([5, 5, 5, 4, 5, 6, 7, 8, 9]) 

tensor([[5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9]]) 

tensor([[5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 4, 5, 6, 7, 8, 9]]) 

tensor([[5, 5],
        [5, 5],
        [5, 5],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]]) 

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]) 



In [34]:
#squezing tensors
print(x,"\n")
z=x+2
z=torch.stack([x,z,z*2])
print(z,"\n")
print(z.squeeze(),"\n")


tensor([5, 5, 5, 4, 5, 6, 7, 8, 9]) 

tensor([[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
        [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
        [14, 14, 14, 12, 14, 16, 18, 20, 22]]) 

tensor([[ 5,  5,  5,  4,  5,  6,  7,  8,  9],
        [ 7,  7,  7,  6,  7,  8,  9, 10, 11],
        [14, 14, 14, 12, 14, 16, 18, 20, 22]]) 

