<a href="https://colab.research.google.com/github/Deepanshu-Malakar/Learn_Machine_Learning/blob/main/intro_to_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)



2.4.0+cu121


In [2]:
#introduction
scalar=torch.tensor(7)
print(scalar)

tensor(7)


Properties of Scalars

In [3]:
#to get dimension of tensor
print("dimension of scalar is :",scalar.ndim)
#to get tensor back as integer
print("value of scalar is: ",scalar.item())

dimension of scalar is : 0
value of scalar is:  7


vector

In [4]:
vector=torch.tensor([7,7])
print(vector)
print("dimension of vector :",vector.ndim)
print("shape of vector : ",vector.shape)
vector2=torch.tensor([[2,4,3],
                     [4,5,3]])
print(vector2)
print("dimension of vector2 :",vector2.ndim)
print("shape of vector2 : ",vector2.shape)

tensor([7, 7])
dimension of vector : 1
shape of vector :  torch.Size([2])
tensor([[2, 4, 3],
        [4, 5, 3]])
dimension of vector2 : 2
shape of vector2 :  torch.Size([2, 3])


Random tensors


In [5]:
random_tensor = torch.rand(4,3,3)
print(random_tensor)

tensor([[[0.9765, 0.4750, 0.4945],
         [0.9440, 0.3850, 0.3169],
         [0.4955, 0.9334, 0.8088]],

        [[0.0157, 0.9532, 0.7681],
         [0.0267, 0.4719, 0.2537],
         [0.6471, 0.6080, 0.4251]],

        [[0.3490, 0.8143, 0.4270],
         [0.9217, 0.9240, 0.1643],
         [0.9107, 0.3223, 0.8080]],

        [[0.5301, 0.2126, 0.2722],
         [0.4820, 0.8461, 0.8014],
         [0.3683, 0.2885, 0.2289]]])


Image tensor

In [6]:
random_image_tensor=torch.rand(size=(224,224,3)) #height width color_channels(rgb)
print("shape: ",random_image_tensor.shape)
print("dimension: ",random_image_tensor.ndim)

shape:  torch.Size([224, 224, 3])
dimension:  3


**Zeroes and Ones**

In [7]:
zeroes=torch.zeros(3,4)
ones=torch.ones(3,4)
print(zeroes)
print("\n")
print(ones)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating Range of tensors

In [8]:
#use torch.arange(start,end,step)   creates an AP with a=start an=end d=step
#  doesnot include the end element
range1=torch.arange(start=1,end=21,step=2)
print(range1)
range2=torch.arange(start=5,end=32,step=4)
print(range2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor([ 5,  9, 13, 17, 21, 25, 29])


Tensors like (creating a tensor with same shape like another tensor)

In [9]:
tensor_like=torch.rand_like(input=random_tensor)
print(tensor_like)

tensor([[[0.6243, 0.7747, 0.3761],
         [0.8427, 0.2766, 0.2829],
         [0.3185, 0.5819, 0.1375]],

        [[0.4087, 0.9808, 0.6963],
         [0.9542, 0.4102, 0.9638],
         [0.7390, 0.8528, 0.1041]],

        [[0.7169, 0.4065, 0.0201],
         [0.9874, 0.7025, 0.8486],
         [0.8138, 0.5847, 0.6472]],

        [[0.9502, 0.5242, 0.6382],
         [0.7719, 0.7837, 0.3171],
         [0.7428, 0.3891, 0.0130]]])


**Getting Information from tensors**
1)Tensor Manupulation *(Tensor operations)*

In [10]:
t=torch.tensor([1,2,3,4])
print("tensor: ",t)
print("tensor + 1: ",t+1)
print("tensor - 1: ",t-1)
print("tensor * 10: ",t*10)
print("tensor / 10: ",t/10)


tensor:  tensor([1, 2, 3, 4])
tensor + 1:  tensor([2, 3, 4, 5])
tensor - 1:  tensor([0, 1, 2, 3])
tensor * 10:  tensor([10, 20, 30, 40])
tensor / 10:  tensor([0.1000, 0.2000, 0.3000, 0.4000])


Matrix Multiplication

In [11]:
#element wise matrix multiplication
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(f"{tensor1}*{tensor2}={tensor1*tensor2}")


tensor([1, 2, 3])*tensor([4, 5, 6])=tensor([ 4, 10, 18])


Dot product of tensors

In [12]:
print(tensor1.matmul(tensor2))
print("note that 32=4+10+18")

tensor(32)
note that 32=4+10+18


In [13]:
tensor1=torch.randint(low=0,high=5,size=(2,3))
tensor2=torch.randint(low=0,high=5,size=(3,4))
print("tensor1:")
print(tensor1)
print("tensor2:")
print(tensor2)
print(f"tensor1 x tensor2 =\n{tensor1.matmul(tensor2)}")

tensor1:
tensor([[3, 4, 0],
        [0, 1, 3]])
tensor2:
tensor([[2, 1, 1, 1],
        [3, 0, 4, 0],
        [4, 3, 4, 4]])
tensor1 x tensor2 =
tensor([[18,  3, 19,  3],
        [15,  9, 16, 12]])


Finding min , max , mean , sum of tensors (tensor aggregation)

In [18]:
print("tensor: ")
print(tensor1)
print(f"min : {tensor1.min()}")
print(f"max : {tensor1.max()}")
print(f"mean : {tensor1.type(torch.float32).mean()}")   #note mean requires float32 type tensor

#to change data type of a tensor write
print("float 32 tensor is: ")
print(tensor1.type(torch.float32))

tensor: 
tensor([[3, 4, 0],
        [0, 1, 3]])
min : 0
max : 4
mean : 1.8333333730697632
float 32 tensor is: 
tensor([[3., 4., 0.],
        [0., 1., 3.]])


# **Positional min and max**
find the position of minimum and maximum element in the tensor.
use argmin() and argmax() functions

In [21]:
print(f"tensor:\n{tensor1}")
print(f"min index : {tensor1.argmin()} and minimum element is {tensor1.min()}")
print(f"max index : {tensor1.argmax()} and maximum element is {tensor1.max()}")

tensor2=torch.tensor([[1,3,5],
                      [6,1,3]])
print("\n")
print(f"tensor:\n{tensor2}")
print(f"min index : {tensor2.argmin()} and minimum element is {tensor2.min()}")
print(f"max index : {tensor2.argmax()} and maximum element is {tensor2.max()}")


tensor:
tensor([[3, 4, 0],
        [0, 1, 3]])
min index : 2 and minimum element is 0
max index : 1 and maximum element is 4


tensor:
tensor([[1, 3, 5],
        [6, 1, 3]])
min index : 0 and minimum element is 1
max index : 3 and maximum element is 6
