<a href="https://colab.research.google.com/github/Deepanshu-Malakar/Learn_Machine_Learning/blob/main/numpy_and_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import torch
print(torch.__version__)

2.4.0+cu121


#**Conversions**
1. How to convert a numpy array into a tensor
2. How to convert a tensor to a numpy array

**Note:** A numpy array default data type is float64 whereas for tensor is float32


In [6]:
array=np.arange(1.0,10.0)
print(f"numpy array is: {array}")
#array to tensor
tensor=torch.from_numpy(array)
print(f"tensor of array is: {tensor}")
#tensor to array
numpy_tensor=tensor.numpy()
print(f"tensor converted back to array is: {numpy_tensor}")

numpy array is: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor of array is: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor converted back to array is: [1. 2. 3. 4. 5. 6. 7. 8. 9.]


#**Checking for GPU**

In [8]:
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


**moving a  tensor to GPU if Available**

In [11]:
tensor=torch.randint(low=3,high=300,size=(3,4))
print(tensor)
tensor_gpu=tensor.to(device)
print(device)  #in my case GPU is not currently available

tensor([[ 75, 288,  85, 223],
        [ 49,  34, 210,  89],
        [ 19,   4, 184, 217]])
cpu


#Moving a tensor back to CPU. But why?
Numpy dosent work on a gpu so in order to perform operations with numpy, you have to move the tensor back to cpu

In [12]:
tensor_cpu=tensor_gpu.cpu().numpy()
print(tensor_cpu)

[[ 75 288  85 223]
 [ 49  34 210  89]
 [ 19   4 184 217]]
